// Code generated by binpack-gen. DO NOT EDIT.

package testdata

import "encoding/binary"

// MarshalPacket 编码 Packet
func MarshalPacket(v *Packet) ([]byte, error) {
	buf := make([]byte, 7)

	binary.BigEndian.PutUint32(buf[0:], v.Magic)

	buf[4] = v.Type

	binary.LittleEndian.PutUint16(buf[5:], v.Length)

	return buf, nil
}

// UnmarshalPacket 解码 Packet
func UnmarshalPacket(data []byte, v *Packet) error {

	v.Magic = binary.BigEndian.Uint32(data[0:])

	v.Type = data[4]

	v.Length = binary.LittleEndian.Uint16(data[5:])

	return nil
}
