// Code generated by binpack-gen. DO NOT EDIT.

package main

import "encoding/binary"

// MarshalGamePacket 编码 GamePacket
func MarshalGamePacket(v *GamePacket) ([]byte, error) {
	buf := make([]byte, 11)

	binary.BigEndian.PutUint32(buf[0:], v.Magic)

	buf[4] = v.Type

	binary.LittleEndian.PutUint16(buf[5:], v.Length)

	binary.BigEndian.PutUint32(buf[7:], v.Data)

	return buf, nil
}

// UnmarshalGamePacket 解码 GamePacket
func UnmarshalGamePacket(data []byte, v *GamePacket) error {

	v.Magic = binary.BigEndian.Uint32(data[0:])

	v.Type = data[4]

	v.Length = binary.LittleEndian.Uint16(data[5:])

	v.Data = binary.BigEndian.Uint32(data[7:])

	return nil
}
